[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = ".svelte-kit/output/client"

[build.environment]
  NODE_VERSION = "20"

# Do NOT put any [[redirects]] blocks here. The adapter and/or _redirects file handles routing.
