# netlify.toml (root)

[build]
# If you're using Yarn 1, --frozen-lockfile is correct
command = "yarn install --frozen-lockfile && yarn build"
# You can omit publish and let the adapter set it, or leave this line:
publish = ".svelte-kit/output/client"

[build.environment]
NODE_VERSION = "20"

# Force all routes to your SvelteKit server function named "server"
[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200
