# netlify.toml (root)
[build]
command = "yarn install --frozen-lockfile && yarn build"
publish = ".svelte-kit/output/client"

[build.environment]
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
external_node_modules = ["mongodb"]
