[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"
