[build]
command = "corepack enable && yarn --version && yarn install --immutable && yarn build"
publish = ".svelte-kit/output/client"

[functions]
node_bundler = "esbuild"
external_node_modules = ["mongodb"]

[[plugins]]
package = "@netlify/plugin-lighthouse"
