# netlify.toml

[build]
command = "yarn install --frozen-lockfile && yarn build"
publish = ".svelte-kit/output/client"

[build.environment]
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
external_node_modules = ["mongodb"]

# Optional: remove while debugging if you want
# [[plugins]]
# package = "@netlify/plugin-lighthouse"
