[build]
  command = "npx svelte-kit build"
  publish = ".svelte-kit/output/client"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_PRODUCTION = "false"
