# Netlify configuration (uses npm)
[build]
  command = "npm run build"
  # For SvelteKit + adapter-netlify, the client assets are here:
  publish = ".svelte-kit/output/client"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION  = "11.4.2"

# Ensure serverless functions use the same Node version
[functions]
  node_bundler = "esbuild"
