services:
  - type: web
    name: charles-boswell-author-site
    runtime: node
    plan: free
    buildCommand: npm install --no-optional && npm run build
    startCommand: node build
    
    # Health check endpoint
    healthCheckPath: /health
    
    envVars:
      # Application Environment
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first --max-old-space-size=4096
      - key: NPM_CONFIG_PRODUCTION
        value: "false"

      # Rollup Fix for Deployment
      - key: ROLLUP_NO_NATIVE
        value: "1"

      # TLS Configuration for MongoDB Atlas
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "1"
      - key: OPENSSL_CONF
        value: ""

      # MongoDB Atlas Configuration
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: Author-site

      # Email Configuration (Gmail SMTP)
      - key: FROM_EMAIL
        value: Charles Boswell <charlesboswell@boswellwebdevelopment.com>
      - key: CONTACT_EMAIL
        value: charlesboswell@boswellwebdevelopment.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: charlesboswell@boswellwebdevelopment.com
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        value: "false"

      # Public Site Configuration
      - key: PUBLIC_BASE_URL
        value: https://author-site-w26m.onrender.com
      - key: PUBLIC_SITE_URL
        value: https://author-site-w26m.onrender.com
      - key: PUBLIC_SITE_NAME
        value: Charles W. Boswell — Author

      # Firebase Configuration (Public)
      - key: PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: PUBLIC_FIREBASE_AUTH_DOMAIN
        value: endless-fire-467204-n2.firebaseapp.com
      - key: PUBLIC_FIREBASE_PROJECT_ID
        value: endless-fire-467204-n2
      - key: PUBLIC_FIREBASE_STORAGE_BUCKET
        value: endless-fire-467204-n2.firebasestorage.app

      # Google Apps Script for Newsletter Backup
      - key: APPS_SCRIPT_URL
        sync: false