// src/lib/config/firebaseTokens.ts - Environment-backed Firebase download tokens
function env(name: string): string {
  return (import.meta as any).env?.[name] || process.env?.[name] || '';
}

export const FIREBASE_TOKENS = {
  BOOKS: {
    FAITH_IN_A_FIRESTORM: env('VITE_FB_TOKEN_BOOKS_FAITH_IN_A_FIRESTORM'),
    CONVICTION_IN_A_FLOOD: env('VITE_FB_TOKEN_BOOKS_CONVICTION_IN_A_FLOOD'),
    HURRICANE_EVE: env('VITE_FB_TOKEN_BOOKS_HURRICANE_EVE'),
    THE_FAITH_OF_THE_HUNTER: env('VITE_FB_TOKEN_BOOKS_THE_FAITH_OF_THE_HUNTER'),
    HEART_OF_THE_STORM: env('VITE_FB_TOKEN_BOOKS_HEART_OF_THE_STORM'),
    SYMBIOGENESIS: env('VITE_FB_TOKEN_BOOKS_SYMBIOGENESIS')
  },
  AUTHOR: {
    PORTRAIT: env('VITE_FB_TOKEN_AUTHOR_PORTRAIT'),
    FIREFIGHTER: env('VITE_FB_TOKEN_AUTHOR_FIREFIGHTER'),
    NAVY: env('VITE_FB_TOKEN_AUTHOR_NAVY'),
    AUGUST_25: env('VITE_FB_TOKEN_AUTHOR_AUGUST_25')
  },
  ICONS: {
    SIGNATURE_LOGO: env('VITE_FB_TOKEN_ICONS_SIGNATURE_LOGO'),
    CHRISTIAN_FICTION: env('VITE_FB_TOKEN_ICONS_CHRISTIAN_FICTION'),
    EPIC_FANTASY: env('VITE_FB_TOKEN_ICONS_EPIC_FANTASY')
  }
} as const;
